name: Build and Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.0

    - name: Extract tag name
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Extract version from tag
      id: get_version
      run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

    - name: Build binaries and package
      env:
        VERSION: ${{ steps.get_version.outputs.version }} # Utilisez le run_id comme version pour cet exemple
      run: |
        version=$VERSION
        echo "Building version $version"
        mkdir build
        echo "---- Building binaries"
        env GOOS=linux GOARCH=amd64 go build -o "build/terraform-provider-securdenvault_${version}_linux_amd64"
        chmod +x "build/terraform-provider-securdenvault_${version}_linux_amd64"
        env GOOS=linux GOARCH=386 go build -o "build/terraform-provider-securdenvault_${version}_linux_386"
        chmod +x "build/terraform-provider-securdenvault_${version}_linux_386"
        env GOOS=windows GOARCH=amd64 go build -o "build/terraform-provider-securdenvault_${version}_windows_amd64.exe"
        env GOOS=windows GOARCH=386 go build -o "build/terraform-provider-securdenvault_${version}_windows_386.exe"

        echo "---- ZIP directory folders"
        cd build
        zip "terraform-provider-securdenvault_${version}_linux_amd64.zip" "terraform-provider-securdenvault_${version}_linux_amd64"
        rm -f "terraform-provider-securdenvault_${version}_linux_amd64"
        zip "terraform-provider-securdenvault_${version}_linux_386.zip" "terraform-provider-securdenvault_${version}_linux_386"
        rm -f "terraform-provider-securdenvault_${version}_linux_386"
        zip "terraform-provider-securdenvault_${version}_windows_amd64.zip" "terraform-provider-securdenvault_${version}_windows_amd64.exe"
        rm -f "terraform-provider-securdenvault_${version}_windows_amd64.exe"
        zip "terraform-provider-securdenvault_${version}_windows_386.zip" "terraform-provider-securdenvault_${version}_windows_386.exe"
        rm "terraform-provider-securdenvault_${version}_windows_386.exe"

        echo "---- Signing documents"
        echo '{
          "version": 1,
          "metadata": {
            "protocol_versions": ["5.0"]
          }
        }' > "terraform-provider-securdenvault_${version}_manifest.json"

        for file in `ls *.zip`; do
            shasum -a 256 $file | sed 's/*//' >> "terraform-provider-securdenvault_${version}_SHA256SUMS"
        done
        shasum -a 256 *.json | sed 's/*//' >> "terraform-provider-securdenvault_${version}_SHA256SUMS"
        
        cd ..

    - name: Setup GPG and sign
      env:
        VERSION: ${{ steps.get_version.outputs.version }}
      run: |
        version=$VERSION
        mkdir -p ~/.gnupg
        echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
        echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
        chmod 700 ~/.gnupg
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --no-tty --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --import
        echo "36AB0929E76749F8C9FE82B3C50AB7CBE7A52C36:6:" | gpg --import-ownertrust
        gpg --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch --no-tty --pinentry-mode loopback --output "build/terraform-provider-securdenvault_${version}_SHA256SUMS.sig" --detach-sig "build/terraform-provider-securdenvault_${version}_SHA256SUMS"

    - name: Install Hub
      run: |
        sudo apt-get update
        sudo apt-get install -y hub

    - name: Upload Release Assets
      run: |
        set -x
        cmd="hub release create"
        for asset in build/*; do
          cmd="$cmd -a $asset"
        done
        cmd="$cmd -d -m \"${{ env.TAG_NAME }}\" \"${{ env.TAG_NAME }}\""
        eval $cmd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-package
        path: build/*